$(document).ready(function(){
    //첫번쨰 제목을 클릭하면 첫번쨰 내용만 보이고,제목에 밑줄나옴
    $('.t1').click(function(){
        //find('a')는 t1의 자식객체 a를 찾아라라는뜻
        $('.t1').find('a').addClass('active');
        $('.t2').find('a').removeClass('active');
        $('.t3').find('a').removeClass('active');
        $('.t4').find('a').removeClass('active');
        $('.t5').find('a').removeClass('active');
        $('.t6').find('a').removeClass('active');
        $('.c1').fadeIn('active');
        $('.c2').hide('active');
        $('.c3').hide('active');
        $('.c4').hide('active');
        $('.c5').hide('active');
        $('.c6').hide('active');
        
    });
    $('.t2').click(function(){
        $('.t1').find('a').removeClass('active');
        $('.t2').find('a').addClass('active');
        $('.t3').find('a').removeClass('active');
        $('.t4').find('a').removeClass('active');
        $('.t5').find('a').removeClass('active');
        $('.t6').find('a').removeClass('active');
        $('.c1').hide('active');
        $('.c2').fadeIn('active');
        $('.c3').hide('active');
        $('.c4').hide('active');
        $('.c5').hide('active');
        $('.c6').hide('active');
    });
    $('.t3').click(function(){
        $('.t1').find('a').removeClass('active');
        $('.t2').find('a').removeClass('active');
        $('.t3').find('a').addClass('active');
        $('.t4').find('a').removeClass('active');
        $('.t5').find('a').removeClass('active');
        $('.t6').find('a').removeClass('active');
        $('.c1').hide('active');
        $('.c2').hide('active');
        $('.c3').fadeIn('active');
        $('.c4').hide('active');
        $('.c5').hide('active');
        $('.c6').hide('active');
    });
    $('.t4').click(function(){
        $('.t1').find('a').removeClass('active');
        $('.t2').find('a').removeClass('active');
        $('.t3').find('a').removeClass('active');
        $('.t4').find('a').addClass('active');
        $('.t5').find('a').removeClass('active');
        $('.t6').find('a').removeClass('active');
        $('.c1').hide('active');
        $('.c2').hide('active');
        $('.c3').hide('active');
        $('.c4').fadeIn('active');
        $('.c5').hide('active');
        $('.c6').hide('active');
    });
    $('.t5').click(function(){
        $('.t1').find('a').removeClass('active');
        $('.t2').find('a').removeClass('active');
        $('.t3').find('a').removeClass('active');
        $('.t4').find('a').removeClass('active');
        $('.t5').find('a').addClass('active');
        $('.t6').find('a').removeClass('active');
        $('.c1').hide('active');
        $('.c2').hide('active');
        $('.c3').hide('active');
        $('.c4').hide('active');
        $('.c5').fadeIn('active');
        $('.c6').hide('active');
    });
    $('.t6').click(function(){
        $('.t1').find('a').removeClass('active');
        $('.t2').find('a').removeClass('active');
        $('.t3').find('a').removeClass('active');
        $('.t4').find('a').removeClass('active');
        $('.t5').find('a').removeClass('active');
        $('.t6').find('a').addClass('active');
        $('.c1').hide('active');
        $('.c2').hide('active');
        $('.c3').hide('active');
        $('.c4').hide('active');
        $('.c5').hide('active');
        $('.c6').fadeIn('active');
    });
});